FROM nickblah/luajit:2.1-beta-alpine3

ENV LUA_PATH "/app/PathOfBuilding/runtime/lua/?.lua;;/app/PathOfBuilding/runtime/lua/?/init.lua;;"
# RUN apk update
# RUN apk add git
# RUN apk add make
# RUN cd /tmp && \
#     git clone https://github.com/keplerproject/luarocks.git && \
#     cd luarocks && \
#     sh ./configure && \
#     make build install && \
#     cd && \
#     rm -rf /tmp/luarocks

RUN  apk add --update git zlib
#unzip curl build-base gcc luarocks5.1 
#lua5.1 lua5.1-dev

WORKDIR /app/
RUN git clone https://github.com/PathOfBuildingCommunity/PathOfBuilding.git
# RUN LUA_PATH='/app/PathOfBuilding/runtime/lua/?.lua;;'
# RUN export LUA_PATH="/app/PathOfBuilding/runtime/lua;"
# RUN export LUA_CPATH="/app/PathOfBuilding/runtime/lua;"
# RUN make PREFIX=/home/myself/lj2
# CMD $LUA_PATH
# RUN luarocks install xml --check-lua-versions
# COPY . .
# COPY ./package.json ./
# RUN npm install

WORKDIR /app/PathOfBuilding/src/

# CMD "ls"
CMD ["luajit", "HeadlessWrapper.lua", "GetScreenSize()"]